style: github
# https://github.com/garden-io/garden/tree/main/.chglog
# https://github.com/git-chglog/git-chglog
# https://github.com/quay/clair/tree/main/.chglog
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/guanguans/music-dl
options:
  sort: semver
  commits:
    sort_by: Scope
    filters:
      Type:
        - build
        # - chore
        - ci
        - docs
        - feat
        - fix
        - perf
        - refactor
        - revert
        - style
        - test
  commit_groups:
    group_by: Type
    sort_by: Custom
    title_order:
      # https://github.com/fobgochod/git-commit-message-format/blob/main/src/main/resources/messages/GitBundle.properties#L37
      - feat
      - fix
      - docs
      - style
      - refactor
      - perf
      - test
      - build
      - ci
      - chore
      - revert
    title_maps:
      # https://github.com/antfu/changelogithub/blob/main/src/config.ts
      # https://github.com/unjs/changelogen/blob/main/src/config.ts
      # https://gitmoji.dev/
      build: ğŸ“¦ Builds
      chore: ğŸ¡ Chores
      ci: ğŸ¤– Continuous Integrations
      docs: ğŸ“– Documents
      feat: âœ¨ Features # ğŸš€ Enhancements
      fix: ğŸ Bug Fixes
      perf: ğŸ Performance Improvements
      refactor: ğŸ’… Code Refactorings
      revert: âªï¸ Reverts
      style: ğŸ¨ Styles
      test: âœ… Tests

      examples: ğŸ€ Examples
      types: ğŸŒŠ Types
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  issues:
    prefix:
      - "#"
  refs:
    actions:
      - Closes
      - Fixes
      - PullRequest
  notes:
    keywords:
      - BREAKING CHANGE
